baseURL = "http://www.chens.life/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "Chen's Life"
copyright = " flyto2035. 本站遵循 CC-BY-NC 4.0 协议"
theme = "diary"
googleAnalytics = "G-XYL6PJ0SX1"
# googleSiteVerification = "xxxx-xxxx"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "base16-snazzy"
    tabWidth = 4
[markup.goldmark.renderer]
    unsafe = true
[params]
subtitle = "不要温柔的走进那个良夜"
enableUtterances = true
enableGitalk = false
disableDarkMode=false
# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "Chen's Life" # will set 'og:site_name'
description = "陈的技术博客"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="relaxcn/blog-comments"
term="title"
label="Utterances-tag"
theme="github-light"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5